server/src/database/entities/block.entity.ts
server/src/database/entities/neighborhood.entity.ts
server/src/database/entities/transaction.entity.ts
server/src/neighborhoods/blocks/block.service.ts
server/src/services/scheduler.service.ts
server/src/utils/database.ts

We use one in test and one locally in dev.

fix: support both postgres and sqlite now

---

server/src/database/entities/block.entity.ts
server/src/dto/block.dto.ts
server/src/neighborhoods/blocks/block.service.ts

feat: Fetching and adding block time to the database

---

client/src/features/neighborhoods/components/blocks.tsx
client/src/features/neighborhoods/components/status.tsx
client/src/features/neighborhoods/components/transactions.tsx

style: Polish up blocks

---

server/src/database/entities/block.entity.ts
server/src/database/entities/transaction.entity.ts
server/src/dto/block.dto.ts
server/src/dto/transaction.dto.ts
server/src/neighborhoods/blocks/block.controller.ts
server/src/neighborhoods/blocks/block.service.ts
server/src/neighborhoods/neighborhood.controller.ts
server/src/neighborhoods/neighborhood.module.ts
server/src/neighborhoods/neighborhood.service.ts
server/src/neighborhoods/transactions/transactions.controller.ts
server/src/neighborhoods/transactions/transactions.module.ts
server/src/neighborhoods/transactions/transactions.service.ts
server/src/utils/convert.ts
server/src/utils/pipes.ts

The route is /api/v1/neighborhoods/:nid/transactions.
There is no details yet.

feat: add transactions controller

---

server/src/neighborhoods/neighborhood.service.ts

In postgresql I could make them both the same query, but SQLite does not support it properly.

perf: Separate the tx count query from fetching neighborhood query

---

server/src/neighborhoods/blocks/block.service.ts

This reverts commit b60047c9ab6745478a4e202420cd80433c28e865.

Revert "perf: better SQL for blocks (#187)"

---

client/src/shared/components/txn-list.tsx

style: Show pretty method names

---

client/src/features/neighborhoods/queries.ts
client/src/shared/components/block-list.tsx
client/src/shared/components/txn-list.tsx
client/src/views/app.tsx
client/src/views/block.tsx
client/src/views/blocks.tsx
client/src/views/index.ts
client/src/views/transaction.tsx
client/src/views/transactions.tsx

Nothing to fetch yet. Will update when the data becomes available.
**Screenshot**

feat: Transaction Details

---

client/src/pages/transaction.tsx

fix: Precision

---

client/src/pages/home/home.tsx
client/src/pages/layout/layout.tsx
client/src/ui/index.ts
client/src/ui/search.tsx

**Placeholder**
**Validates as you type**
**Works for block height**
**Works for transaction hashes**
**Works for addresses, including subresources**

feat: Search bar on homepage

---

server/.env
server/src/data/data-exporter.ts
server/src/data/data.controller.ts
server/src/database/entities/block.entity.ts
server/src/database/entities/transaction-details.entity.ts
server/src/dto/address.dto.ts
server/src/neighborhoods/addresses/addresses.controller.ts
server/src/neighborhoods/addresses/addresses.module.ts
server/src/neighborhoods/addresses/addresses.service.ts
server/src/neighborhoods/neighborhood.module.ts
server/src/services/scheduler/neighborhood-updater/updater.ts
server/src/services/scheduler/tx-analyzer.service.ts
server/src/services/scheduler/tx/idstore.store.ts
server/src/services/scheduler/tx/ledger.send.ts
server/src/utils/pipes.ts

Also rewrite some columns into the proper JSON type.
This requires a reset of the database, so I won't merge it right away.

feat: add addresses field and controllers

---

server/src/services/scheduler/tx-analyzer.service.ts

fix: dont set attributes if there are none

---

server/src/data/data-exporter.ts

fix: use a stream instead of downloading the whole data

---

server/src/neighborhoods/blocks/block.controller.ts
server/src/neighborhoods/blocks/block.service.ts
server/src/utils/pipes.ts

Will try parse Integer first, since 123456 is also a valid hexadecimal.

feat: allow block height for bhash too

---

client/src/api/neighborhood-provider.tsx

fix: Default to Manifest Ledger in production

---

client/src/pages/transaction/idstore-store.tsx
client/src/pages/transaction/index.ts
client/src/pages/transaction/ledger-send.tsx
client/src/pages/transaction/transaction.tsx

Now parsing and displaying `idstore.store`.

feat: Details for IDStore.Store

---

client/src/pages/transaction/basics.tsx
client/src/pages/transaction/details.tsx
client/src/pages/transaction/index.ts
client/src/pages/transaction/multisig.tsx
client/src/pages/transaction/transaction.tsx

- Proposals show the proposed transaction.
- Approve, withdraw, revoke just show the transaction token.

feat: Multisig Details

---

client/src/pages/transaction/ledger-send.tsx
client/src/pages/transaction/tokens-mint-burn.tsx
client/src/pages/transaction/tokens.tsx

- Apply precision
- Right align numbers
- Abstract out `findToken` function

style: Better Mint/Burn details

---

README.md
server/src/auth/auth.module.ts
server/src/dto/neighborhood.dto.ts
server/src/neighborhoods/neighborhood.controller.ts
server/src/neighborhoods/neighborhood.service.ts

Also added some more logging and API constraints to clarify things.

doc: add documentation for how to use the login and JWT

---

client/src/pages/transaction/transaction.tsx

Fixing small bug in request/response fields in transactions view. 
Fixed data.response reference. 
Fixes # (issue)
- Local testing
- None, minor change.

bugfix: Fixing response in transaction details

---

client/src/pages/metrics/networkMetrics.tsx

Added section to metrics dashboard for decentralized web hosting metrics. 
Added charts to networkMetrics page layout
Tested locally against a clone of prod database.
none

feat: Adding decentralized web hosting metrics

---

client/src/pages/metrics/networkMetrics.tsx
client/src/utils/index.ts

Adding more GPU stats to network metrics.
Total CUDA cores
Total memory
- Tested locally against a clone of prod
None

feat: Adding more GPU stats

---

client/src/pages/metrics/metrics.tsx
client/src/pages/metrics/networkMetrics.tsx

- Added Kubernetes metrics to the dashboard
Fixes # (issue)
- Tested locally against a clone of prod data

Feat/Kubernetes Metrics

---

client/src/pages/home/status.tsx
client/src/pages/metrics/networkMetrics.tsx
server/src/metrics/systemwide/systemwide.service.ts
server/src/services/metrics-scheduler/metrics-scheduler.service.ts

Added Active Addresses database count metric to metrics 
Updated query for totalsitescount to pull from new manifest-exporter prometheus metric
Set legacy network status to "inactive" 
Fixes # (issue)
https://github.com/liftedinit/talib/issues/269 
Tested locally against a clone of prod 
None

Feat/active addresses metric, legacy network status, 

---

server/src/database/entities/token.entity.ts
server/src/dto/token.dto.ts
server/src/neighborhoods/tokens/tokens.service.ts
server/src/services/scheduler/neighborhood-updater/updater.ts
server/src/utils/network/ledger.ts

This pull request introduces several enhancements and fixes related to token supply management and the neighborhood updater functionality. The changes primarily involve adding new fields to the `Token` entity and DTOs, updating the neighborhood updater to handle token supply, and extending the ledger utility functions.
* [`server/src/database/entities/token.entity.ts`](diffhunk://#diff-41dac6f2896820c2c4d3b1af8112ebe28695cea9b924300d39c8dc97934dcce1R28-R42): Added `totalSupply` and `circulatingSupply` fields to the `Token` entity and included them in the `intoDto` method.
* [`server/src/dto/token.dto.ts`](diffhunk://#diff-2f43f2396f26e1844685f8ce12657e9be799b508bc3e12337fe59ebf0ebf8093R19-R24): Added `totalSupply` and `circulatingSupply` properties to both `TokenDto` and `TokenDetailsDto` …

feat: add token supply to tokens endpoint and display

---

server/src/app.module.ts
server/src/database/entities/migration-whitelist.entity.ts
server/src/dto/migration-whitelist.dto.ts
server/src/neighborhoods/migrations/migration-whitelist.controller.ts
server/src/neighborhoods/migrations/migration-whitelist.service.ts
server/src/neighborhoods/migrations/migrations.module.ts

This pull request introduces a new feature for managing a migration whitelist in the application. The changes include adding a new entity, DTO, controller, and service to handle the migration whitelist functionality.
* **Entity Addition**:
* [`server/src/database/entities/migration-whitelist.entity.ts`](diffhunk://#diff-c193998fa296f7a2c0e740ce3fa1805b3b90d4692c68b31beb66689527d953e4R1-R18): Added a new entity `MigrationWhitelist` to represent whitelist entries with a unique manifest address.
* [`server/src/app.module.ts`](diffhunk://#diff-4e8033eb0f9fd87924c445b7ac0f1c1192d4890fc1589b2fad2679797d4f4ce0R37): Imported and registered the `MigrationWhitelist` entity. [[1]](diffhunk://#diff-4e8033eb0f9fd87924c445b7ac0f1c1192d4890fc1589b2fad2679797d4f4ce0R37) …

feat: migration whitelist

---

server/.env
server/src/config/app/configuration.service.ts
server/src/config/app/configuration.ts
server/src/main.ts

This pull request introduces support for configuring Cross-Origin Resource Sharing (CORS) in the server application. The changes include defining a new environment variable for allowed origins, updating the configuration service to handle this variable, and enabling CORS in the application bootstrap process.
* [`server/.env`](diffhunk://#diff-851502e39b7ba2dbf4da21e578181c158ff8917752cefcae5996bd989915e25dR5-R6): Added `APP_CORS_ORIGIN` environment variable to specify allowed origins for CORS. If not set, defaults to `"*"`.
* [`server/src/config/app/configuration.ts`](diffhunk://#diff-9dce7d0fef8a48e80c32cb32391d5b184647fc8341c69047c4a61c93a5568fd7R9-R11): Updated the application configuration to parse `APP_CORS_ORIGIN` into an array of origins or default to `"*"`.
* …

feat: enable cors across the app
